// ──────────────────────────────────────────────────────────────────────────────
// Vinted selectors — VERIFIED against live logged-in UI (April 2026).
//
// VERIFIED via accessibility-tree inspection of a real Vinted account:
//   • Vinted is Next.js App Router + RSC — initial HTML is hydration skeleton.
//   • Design system class prefix: "web_ui__*" (e.g. web_ui__Text__text).
//   • Inbox URL: /inbox
//   • Conversation URL: /inbox/{numericConversationId}
//   • Item URL: /items/{id}-{slug}
//   • Conversation sidebar items are <button>, NOT <a href>. SPA navigation
//     via onClick. We can't scrape hrefs — we scrape the conversation id
//     from the URL after clicking, OR from the user_id link inside.
//   • Inbox header unread count: aria-label pattern "N neue Nachrichten".
//   • Offer message pattern (auto-generated by Vinted, NOT free text):
//       "Hi! Würdest du mir diese(n) Artikel für {X,XX} € verkaufen?"
//     The offer-amount is rendered as a separate `generic` element
//     (e.g. "23,20 €") together with the original price crossed out.
//   • Action buttons in the offer region expose INNER text (not aria-label):
//       "Annehmen" / "Ablehnen" / "Mach dein Preisangebot"
//   • Message compose textarea placeholder: "Schreibe hier deine Nachricht"
//   • Member-info block contains "Members location {country}, {city}" — this
//     is the COARSE location (city-level only). Full shipping address is
//     only exposed in the transaction detail after payment.
//
// STILL UNVERIFIED (requires a completed sale in the test account):
//   • Exact URL + selectors for buyer's full shipping address (sold_items
//     URL `/member/general/sold_items` is DEAD / 404 in April 2026).
//     TODO: when a real sale closes, inspect the transaction-detail URL.
//   • Shipping-label download selector.
//
// Strategy: comma-separated fallback chains, most specific first.
// Playwright `locator()` takes the first match.
// ──────────────────────────────────────────────────────────────────────────────

export const VINTED = {
  // ── URLs (verified) ───────────────────────────────────────────────────────
  inboxUrl: '/inbox',
  loginUrl: '/member/signup/select_type',
  // CAUTION: /member/general/sold_items returns 404 — legacy URL.
  // Update once the live path is confirmed via the user's profile menu.
  soldItemsUrl: '/member/transactions',

  // ── Auth ──────────────────────────────────────────────────────────────────
  loginButton: [
    '[data-testid="header-login-button"]',
    'a[href*="/member/signup/select_type"]',
    'text=/einloggen|anmelden|log in/i',
  ].join(', '),

  // Any of these visible = user is logged in.
  // VERIFIED: logged-in users see the "13 neue Nachrichten" inbox link
  // in the header (the unread-count wording is stable; the number varies).
  loggedInIndicator: [
    'a[href="/inbox"]',                           // always present when auth'd
    'header button:has(img[alt])',                // profile-pic button (alt = username)
    '[data-testid="header-user-profile-button"]',
  ].join(', '),

  // ── Consent dialog (appears on first visit in a fresh session) ────────────
  // Dismiss with "Alle zulassen" OR "Notwendige auswählen". Bot prefers the
  // privacy-preserving option.
  consentDialog: 'dialog[aria-label*="Privatsphäre"], dialog[aria-label*="Privacy"]',
  consentAcceptNecessary: [
    'button:has-text("Notwendige auswählen")',
    'button:has-text("Only necessary")',
  ].join(', '),

  // ── Item card (catalog / search) ──────────────────────────────────────────
  itemCard: [
    '[data-testid="item-card"]',
    '.new-item-box__container',
    'a[href^="/items/"]',
  ].join(', '),
  itemCardTitle: '[data-testid="item-card-title"], .new-item-box__title',
  itemCardPrice: '[data-testid="item-card-price"], .new-item-box__price',

  // ── Inbox list (sidebar) ──────────────────────────────────────────────────
  // IMPORTANT: these are <button> elements, NOT anchors. They do not expose
  // an href — the conversation id is only available after the click lands
  // on /inbox/{id}. Scrape the id from `page.url()` after click.
  //
  // The most reliable pattern (verified April 2026) is a <button> inside <main>
  // that contains an avatar image (img[alt=username]) and is NOT the
  // category/nav tab bar.
  conversationListItem: [
    '[data-testid^="conversation-list-item"]',
    'main button:has(img[alt]):not([role="tab"])',
  ].join(', '),

  // Within a conversation-list-item button, the first inner `generic`
  // with plain text is the username. These helper selectors are relative
  // to the conversationListItem.
  conversationUsername:
    '[data-testid="conversation-user-name"], img + div, span:first-child',
  conversationDate:
    '[data-testid="conversation-last-message-date"], span:nth-of-type(2)',
  conversationSnippet:
    '[data-testid="conversation-last-message"], span:last-child',

  // Unread count in header (global).
  inboxHeaderLink: 'a[href="/inbox"]',
  inboxUnreadAriaLabelRegex: /^(\d+)\s+neue\s+Nachricht(en)?$/i,

  // ── Conversation view ─────────────────────────────────────────────────────
  // VERIFIED: auto-generated offer text.
  // Matches the Vinted bot message. The price is captured in group 1.
  offerMessageTextRegex:
    /Hi!\s+Würdest du mir diese\(n\) Artikel für\s+([\d.,]+)\s*€\s+verkaufen\?/i,

  // Message bubbles — Vinted renders plain text as `generic` role.
  messageList: '[data-testid="message-list"], [role="log"], main',
  messageItem: [
    '[data-testid="message-item"]',
    '[data-message-id]',
    // Fallback: chronologically-ordered generics inside the conversation.
    'main > div:has(> img[alt]) ~ div > div',
  ].join(', '),
  messageBody: '[data-testid="message-body"], p, span',

  // Offer action buttons. Text match is the MOST RELIABLE signal — Vinted
  // doesn't put data-testid here, but the German localized strings are stable.
  offerAcceptButton: [
    '[data-testid="offer-accept-button"]',
    'button:has-text("Annehmen")',
    'button:has-text("Accept")',
  ].join(', '),
  offerDeclineButton: [
    '[data-testid="offer-decline-button"]',
    'button:has-text("Ablehnen")',
    'button:has-text("Decline")',
  ].join(', '),
  offerCounterButton: [
    'button:has-text("Mach dein Preisangebot")',
    'button:has-text("Make a counter offer")',
    'button:has-text("Verhandeln")',
  ].join(', '),

  // Displayed offer amount (the live price the buyer proposed).
  // Typically the first "€"-suffixed generic that isn't crossed-out.
  offerAmount: [
    '[data-testid="offer-amount"]',
    'main span:has-text(/^\\d+[.,]?\\d*\\s*€$/)',
  ].join(', '),

  // ── Item header inside conversation ───────────────────────────────────────
  // The linked product (so we can map the chat → our Listings table by URL).
  conversationItemLink: 'main a[href^="/items/"], main a[href*="/items/"]',
  conversationItemTitle: 'main h2, main h3',
  conversationItemListPrice: 'main p, main span',     // generic — rely on context

  // ── Member-info block (shown above messages) ──────────────────────────────
  // VERIFIED: `generic "Members location {country}, {city}"` — coarse only.
  memberLocationText: 'text=/Members?\\s+location/i',

  // ── Compose area ──────────────────────────────────────────────────────────
  textInput: 'textarea[placeholder="Schreibe hier deine Nachricht"], textarea',
  sendButton: [
    'button[data-testid="send-message-button"]',
    'button[aria-label*="senden" i]',
    'button:has-text("Senden")',
  ].join(', '),

  // ── Sold items / transaction detail ───────────────────────────────────────
  // UNVERIFIED — selectors below are placeholders. When a real sale closes,
  // inspect the live URL and adjust. For now the bot won't auto-extract
  // the buyer address; it marks the sale as requiring MANUAL address entry
  // via the dashboard if auto-extraction fails.
  buyerName: '[data-testid="buyer-name"], [data-testid="transaction-buyer"]',
  buyerAddress: '[data-testid="buyer-address"], [data-testid="transaction-shipping-address"]',
  shippingLabelLink:
    'a[data-testid="shipping-label-download"], a[href*="shipping_label"], a:has-text("Versandetikett")',
  orderPaidIndicator:
    '[data-testid="order-status-paid"], [data-testid="transaction-status-paid"], text=/bezahlt|paid/i',
} as const;
